config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'users/:id/saved_search_results', to: 'users#saved_search_results', as: 'saved_search_results_user'
    get 'users/:id/saved_searches', to: 'users#saved_searches', as: 'saved_searches_user'
  end

  namespace :saved_search_results do
    post 'update_link'
    post 'updated'
    post 'denied'
    post 'create'
    delete 'destroy'
  end

  namespace :saved_searches do
    get 'new'
    delete 'destroy'
    post 'viewed'
    post 'refresh'
    get 'redis_info'
    post 'del_redis_key'
  end

  post 'we_work_remotelies', to: 'saved_searches#create'
  post 'jr_dev_jobs_index', to: 'saved_searches#create'

  root to: "static_pages#home"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    # Scraper.scrape_all
    # @saved_searches = current_user ? current_user.saved_searches : []
    @all_job_searches = JobSearch.all
  end

end

app/views/static_pages/home.html.haml
.row
  .col-md-10.col-md-offset-1
    %h1.text-center
      Tired of checking 10+ job sites daily for tech jobs!
    %h4.text-center
      Let me check for you. All you need to do to start is
      - if current_user
        = link_to 'created saved searches', users_saved_searches_new_path(current_user)
      - else
        = link_to 'sign up', new_user_registration_path
.row
  .col-md-10.col-md-offset-1
    %h3.text-center
      I am adding new sites to scrape all the time!
    %h2.text-center
      Right now I can check the below sites.
.row
  - @all_job_searches.each do |job_search|
    .col-md-4
      %a{href: job_search.homepage, target: '_blank'}
        = image_tag job_search.image, class: 'job-logo'
.row
  .col-md-10.col-md-offset-1
    %h2.text-center
      Your saved searches get checked once per day and you will get an email if any new searches were found.