config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    get 'users/:id/saved_search_results', to: 'users#saved_search_results', as: 'saved_search_results_user'
    get 'users/:id/saved_searches', to: 'users#saved_searches', as: 'saved_searches_user'
  end

  namespace :saved_search_results do
    post 'update_link'
    post 'updated'
    post 'denied'
    post 'create'
    delete 'destroy'
  end

  namespace :saved_searches do
    get 'new'
    delete 'destroy'
    post 'viewed'
    post 'refresh'
    get 'redis_info'
    post 'del_redis_key'
  end

  post 'we_work_remotelies', to: 'saved_searches#create'
  post 'jr_dev_jobs_index', to: 'saved_searches#create'

  root to: "static_pages#home"
end

app/views/layouts/_messages.html.haml
:javascript
  $(document).ready(function() {setTimeout(function(){
      $('.flash-msg').fadeOut("slow");
    }, 3000);

  });
.row.flash-msg
  .col-md-12
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        %ul.no-bullets
          %li
            = value

app/views/layouts/_top_nav.html.haml
.row
  .col-md-12
    %nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#{root_path}"}
            = image_tag("crosshairs.png", :alt => "Job Hunt", id: 'brand-icon')
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          - selected = params["controller"] + "_" + params["action"]
          %ul.nav.navbar-nav
            - if current_user
              %li{:role => "presentation", class: "#{'active' if selected == 'saved_searches_new' }"}
                %a{:href => "#{saved_searches_new_path}"}
                  New Saved Search
              %li{:role => "presentation", class: "#{'active' if selected == 'users_saved_searches' }"}
                %a{:href => "#{saved_searches_user_path(current_user)}"}
                  Saved Searches
              %li{:role => "presentation", class: "#{'active' if selected == 'users_saved_search_results' }"}
                %a{:href => "#{saved_search_results_user_path(current_user)}"}
                  Applied Jobs
              - if current_user.admin?
                %li{:role => "presentation", class: "#{'active' if selected == 'saved_searches_redis_info_path' }"}
                  %a{:href => "#{saved_searches_redis_info_path}"}
                    Saved Redis Results
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = current_user.email
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    = link_to "Edit Account", edit_user_registration_path
                  %li.divider
                  %li
                    = link_to "Logout", destroy_user_session_path, :method => :delete
            - else
              %li
                %a{:href => "#{new_user_registration_path}"}
                  Sign Up
              %li
                %a{:href => "#{new_user_session_path}"}
                  Sign In

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "#{$domain_name}"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css", :rel => "stylesheet"}
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    .container-fluid
      .row.spacer
        .col-md-12
      = render 'layouts/messages'
      = render partial: 'layouts/top_nav'
      .row
        .col-md-10.col-sm-offset-1
          = yield
      - if Rails.env == 'development'
        .row
          .col-md-12
            %br
            %br
            = debug params